export enum AgentType {
  WORD_DISCOVERY = 'WORD_DISCOVERY',
  CONTEXT = 'CONTEXT',
  WRITING = 'WRITING',
  REWRITE = 'REWRITE',
  LANGUAGE_CHECKER = 'LANGUAGE_CHECKER',
  WORD_COMPARE = 'WORD_COMPARE',
  DIALECT = 'DIALECT',
  MODERN_VOCABULARY = 'MODERN_VOCABULARY',
  LANGUAGE_BRIDGE = 'LANGUAGE_BRIDGE',
  ACCESSIBILITY = 'ACCESSIBILITY',
  RAG = 'RAG',
}
